In [1]:
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt

In [2]:
files = os.listdir('bsp')
files = [x for x in files if ('.D' not in x) and ('checkpoints' not in x)]
# files=files[-1:]
files.sort()
print(files)
for file in files:
    if(file==files[0]):
        print(True)
        df = pd.read_csv('bsp/'+file)
        df['date']=pd.to_datetime(df['date']).astype(str)
        
    else:
        df_temp = pd.read_csv('bsp/'+file)
        df_temp['date']=pd.to_datetime(df_temp['date']).astype(str)
        df = pd.concat([df,df_temp])


df = df.rename(columns={'track':'Track','name':'DogName'})

df['Track']=df['Track'].str.strip()
df['DogName']=df['DogName'].str.strip()
df['date']=df['date'].str.strip()


df['menu_day'] = df['MENU_HINT'].str.extract(r'(\d{1,2})\D+(\w+)')[0].astype(str)
df['menu_month']=df['MENU_HINT'].str.split(' ').str[-1].str[:3]
df['menu_yr']=df['date'].str[:4]

df['date']=df['menu_day']+'-'+df['menu_month']+'-'+df['menu_yr'].astype(str)
df['date']=pd.to_datetime(df['date'],format="%d-%b-%Y", errors='coerce').astype(str)
df = df.dropna(subset=['date'])
df = df.drop(['menu_day', 'menu_month', 'menu_yr'], axis=1)
df

['bsp2018.csv', 'bsp2019.csv', 'bsp2020.csv', 'bsp2021.csv', 'bsp2022.csv', 'bsp2023.csv', 'bsp2024.csv', 'bsp2025.csv']
True

,Unnamed: 0,Track,MENU_HINT,date,DogName,BSP,MORNINGWAP,PPTRADEDVOL
0,1,shepparton,AUS / Shep (AUS) 31st May,2018-05-31,stella view,23.645034,20.737885,0.00
1,2,shepparton,AUS / Shep (AUS) 31st May,2018-05-31,bear cabang,133.614102,46.303718,0.00
2,3,maitland,AUS / Mait (AUS) 31st May,2018-05-31,potters flash,52.393295,23.380410,0.00
3,4,ballarat,AUS / Ball (AUS) 31st May,2018-05-31,cosmic spur,6.400000,1.000000,0.00
4,5,sandown park,AUS / SPrk (AUS) 31st May,2018-05-31,shaes intention,12.549408,8.239423,0.00
...,...,...,...,...,...,...,...,...
31145,2207,bendigo,Bendigo (AUS) 8th Mar,2024-03-08,wheres walter,5.170479,2.848700,1698.64
31146,2208,bendigo,Bendigo (AUS) 8th Mar,2024-03-08,silky sauce,1.473865,1.277500,30443.47
31147,2211,the gardens,The Gardens (AUS) 8th Mar,2024-03-08,ted robbo,2.401818,2.003400,5149.88
31148,2214,wagga,Wagga (AUS) 8th Mar,2024-03-08,cawbourne mocha,135.485202,45.728400,105.60
31149,2215,mandurah,Mandurah (AUS) 8th Mar,2024-03-08,mashle wave,3.759012,1.000000,4477.40

In [3]:
trks = ['richmond straight','shepparton', 'maitland', 'ballarat', 'sandown park', 'goulburn', 'hobart', 'dapto', 'angle park', 'warrnambool', 'warragul', 'albion park', 'northam', 'traralgon', 'healesville', 'richmond', 'ipswich', 'geelong', 'casino', 'the gardens', 'cannington', 'mount gambier', 'dubbo', 'bendigo', 'bulli', 'horsham', 'wentworth park', 'the meadows', 'sale', 'darwin', 'gawler', 'grafton', 'nowra', 'bathurst', 'launceston', 'townsville', 'devonport', 'lismore', 'rockhampton', 'cranbourne', 'strathalbyn', 'wagga', 'cairns', 'mandurah', 'temora', 'gosford', 'capalaba', 'murray bridge', 'angle park', 'ipswich', 'bundaberg', 'gunnedah', 'taree']
races = pd.read_csv('allRaces1.csv')
races = races[races['Track'].isin(trks)]

char = "'"
races['DogName']=races['DogName'].str.replace(char,'').str.replace('.','')

races['Track']=races['Track'].str.strip()
races['DogName']=races['DogName'].astype(str).str.strip()
races['date']=races['date'].astype(str).str.strip()



races2 = pd.merge(races,df,on=['DogName','date','Track'],how='left')
races2 = races2.dropna(subset=['Place'])
races2

/var/folders/_5/kty37fps3g723664y0dwx0_80000gn/T/ipykernel_14218/1386800230.py:6: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  races['DogName']=races['DogName'].str.replace(char,'').str.replace('.','')

,Place,DogName,Box,Weight,StartPrice,PIR,Split,RunTime,RaceId,Distance,RaceGrade,Track,date,TrainerLName,TrainerFName,Unnamed: 0,MENU_HINT,BSP,MORNINGWAP,PPTRADEDVOL
0,1.0,raine allen,1.0,27.4,2.4,111,6.68000,28.660,335811282,500,Restricted Win,bendigo,2018-07-01,Grenfell,C,457.0,AUS / Bend (AUS) 1st Jul,2.485728,2.402235,0.00
1,2.0,surf a lot,2.0,32.8,6.3,332,7.01000,28.820,335811282,500,Restricted Win,bendigo,2018-07-01,Tyley,C,119.0,AUS / Bend (AUS) 1st Jul,10.000000,8.224462,0.00
2,3.0,pingin bee,6.0,25.5,9.3,443,7.24000,28.930,335811282,500,Restricted Win,bendigo,2018-07-01,Dapiran,P,746.0,AUS / Bend (AUS) 1st Jul,12.362569,8.322981,0.00
3,4.0,lucas the great,7.0,32.2,9.1,655,7.31000,29.030,335811282,500,Restricted Win,bendigo,2018-07-01,Hamilton,E,520.0,AUS / Bend (AUS) 1st Jul,8.013214,5.076427,0.00
4,5.0,quavo,4.0,28.9,3.4,766,7.38000,29.050,335811282,500,Restricted Win,bendigo,2018-07-01,Dapiran,P,392.0,AUS / Bend (AUS) 1st Jul,3.820639,2.578982,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1787885,1.0,black ombre,8.0,33.0,3.7,311.0,6.61875,27.071,1001129401,485,4,horsham,2024-03-08,poo,poo,1713.0,Horsham (AUS) 8th Mar,3.600000,2.898200,7270.39
1787888,1.0,wrong bias,1.0,28.9,1.6,11.0,10.20000,23.070,1003096223,410,4,horsham,2024-03-08,poo,poo,1489.0,Horsham (AUS) 8th Mar,1.812544,1.643800,15206.80
1787889,2.0,hidden stones,2.0,30.6,2.5,22.0,10.27000,23.135,1003096223,410,4,horsham,2024-03-08,poo,poo,953.0,Horsham (AUS) 8th Mar,2.573757,1.846300,10763.64
1787890,6.0,miss verdansky,4.0,28.5,52.5,76.0,11.05925,23.813,1003096223,410,5,horsham,2024-03-08,poo,poo,323.0,Horsham (AUS) 8th Mar,190.000000,87.550400,145.98
1787891,3.0,happy potter,4.0,32.5,101.0,254.0,11.64000,23.700,1004319650,400,5,the gardens,2024-03-08,poo,poo,1966.0,The Gardens (AUS) 8th Mar,195.653973,24.485000,53.01

In [4]:
nonjoin = races2[races2['BSP'].isna()]
nonjoin

,Place,DogName,Box,Weight,StartPrice,PIR,Split,RunTime,RaceId,Distance,RaceGrade,Track,date,TrainerLName,TrainerFName,Unnamed: 0,MENU_HINT,BSP,MORNINGWAP,PPTRADEDVOL
342,1.0,mount duke,6.0,33.2,15.0,NaN,NaN,30.51,334311904,512,Maiden,mount gambier,2018-07-01,Perry,N,NaN,NaN,NaN,NaN,NaN
343,2.0,teacup toni,5.0,28.2,3.5,NaN,NaN,30.64,334311904,512,Maiden,mount gambier,2018-07-01,Weis,B,NaN,NaN,NaN,NaN,NaN
344,3.0,bourne bill,2.0,30.5,4.6,NaN,NaN,30.66,334311904,512,Maiden,mount gambier,2018-07-01,Peckham,D,NaN,NaN,NaN,NaN,NaN
345,4.0,go saints,8.0,27.3,10.0,NaN,NaN,30.76,334311904,512,Maiden,mount gambier,2018-07-01,Wilson,W,NaN,NaN,NaN,NaN,NaN
346,5.0,little lina,1.0,27.4,12.0,NaN,NaN,30.92,334311904,512,Maiden,mount gambier,2018-07-01,Fennell,D,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1787636,1.0,vintage dot,3.0,25.7,1.0,0.0,5.26,30.24,1003936442,515,6,launceston,2024-03-08,poo,poo,NaN,NaN,NaN,NaN,NaN
1787637,3.0,motton lass,5.0,27.9,1.0,0.0,5.38,30.40,1003936442,515,Maiden,launceston,2024-03-08,poo,poo,NaN,NaN,NaN,NaN,NaN
1787638,1.0,frayahs bailey,1.0,27.9,1.0,0.0,5.25,30.10,1003936443,515,Maiden,launceston,2024-03-08,poo,poo,NaN,NaN,NaN,NaN,NaN
1787639,3.0,just like comet,3.0,24.9,1.0,0.0,5.20,30.76,1003936443,515,Maiden,launceston,2024-03-08,poo,poo,NaN,NaN,NaN,NaN,NaN
1787640,2.0,theme,5.0,28.1,1.0,0.0,5.25,30.56,1003936443,515,Maiden,launceston,2024-03-08,poo,poo,NaN,NaN,NaN,NaN,NaN

In [5]:
races2 = races2.drop_duplicates(keep='first')
races2.to_csv('bsp_allRaces.csv')
races2

,Place,DogName,Box,Weight,StartPrice,PIR,Split,RunTime,RaceId,Distance,RaceGrade,Track,date,TrainerLName,TrainerFName,Unnamed: 0,MENU_HINT,BSP,MORNINGWAP,PPTRADEDVOL
0,1.0,raine allen,1.0,27.4,2.4,111,6.68000,28.660,335811282,500,Restricted Win,bendigo,2018-07-01,Grenfell,C,457.0,AUS / Bend (AUS) 1st Jul,2.485728,2.402235,0.00
1,2.0,surf a lot,2.0,32.8,6.3,332,7.01000,28.820,335811282,500,Restricted Win,bendigo,2018-07-01,Tyley,C,119.0,AUS / Bend (AUS) 1st Jul,10.000000,8.224462,0.00
2,3.0,pingin bee,6.0,25.5,9.3,443,7.24000,28.930,335811282,500,Restricted Win,bendigo,2018-07-01,Dapiran,P,746.0,AUS / Bend (AUS) 1st Jul,12.362569,8.322981,0.00
3,4.0,lucas the great,7.0,32.2,9.1,655,7.31000,29.030,335811282,500,Restricted Win,bendigo,2018-07-01,Hamilton,E,520.0,AUS / Bend (AUS) 1st Jul,8.013214,5.076427,0.00
4,5.0,quavo,4.0,28.9,3.4,766,7.38000,29.050,335811282,500,Restricted Win,bendigo,2018-07-01,Dapiran,P,392.0,AUS / Bend (AUS) 1st Jul,3.820639,2.578982,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1787885,1.0,black ombre,8.0,33.0,3.7,311.0,6.61875,27.071,1001129401,485,4,horsham,2024-03-08,poo,poo,1713.0,Horsham (AUS) 8th Mar,3.600000,2.898200,7270.39
1787888,1.0,wrong bias,1.0,28.9,1.6,11.0,10.20000,23.070,1003096223,410,4,horsham,2024-03-08,poo,poo,1489.0,Horsham (AUS) 8th Mar,1.812544,1.643800,15206.80
1787889,2.0,hidden stones,2.0,30.6,2.5,22.0,10.27000,23.135,1003096223,410,4,horsham,2024-03-08,poo,poo,953.0,Horsham (AUS) 8th Mar,2.573757,1.846300,10763.64
1787890,6.0,miss verdansky,4.0,28.5,52.5,76.0,11.05925,23.813,1003096223,410,5,horsham,2024-03-08,poo,poo,323.0,Horsham (AUS) 8th Mar,190.000000,87.550400,145.98
1787891,3.0,happy potter,4.0,32.5,101.0,254.0,11.64000,23.700,1004319650,400,5,the gardens,2024-03-08,poo,poo,1966.0,The Gardens (AUS) 8th Mar,195.653973,24.485000,53.01

In [10]:
races3 = races2[races2['Track']=='shepparton']
races3 = races3[races3['date']=='2024-03-05']
races3[races3['RaceId']==1003071153]

,Place,DogName,Box,Weight,StartPrice,PIR,Split,RunTime,RaceId,Distance,RaceGrade,Track,date,TrainerLName,TrainerFName,Unnamed: 0,MENU_HINT,BSP,MORNINGWAP,PPTRADEDVOL
1784107,5.0,shaye jay,1.0,25.2,14.1,34.0,8.7070,23.010,1003071153,390,5,shepparton,2024-03-05,poo,poo,112.0,Shepparton (AUS) 5th Mar,25.052351,16.2487,1147.13
1784108,1.0,found a spot,2.0,31.1,1.7,11.0,8.4200,22.113,1003071153,390,5,shepparton,2024-03-05,poo,poo,1513.0,Shepparton (AUS) 5th Mar,1.650000,1.5510,18889.09
1784119,6.0,gunai redeemer,8.0,29.0,18.3,27.0,8.7000,23.120,1003071153,390,5,shepparton,2024-03-05,poo,poo,1015.0,Shepparton (AUS) 5th Mar,17.832759,15.1977,1524.09
1784120,2.0,impassioned,7.0,25.8,7.8,52.0,8.7420,22.751,1003071153,390,5,shepparton,2024-03-05,poo,poo,1716.0,Shepparton (AUS) 5th Mar,11.766773,8.3167,2088.12
1784121,7.0,pablos star,6.0,33.3,32.9,45.0,8.7245,23.145,1003071153,390,5,shepparton,2024-03-05,poo,poo,745.0,Shepparton (AUS) 5th Mar,146.038752,73.8128,248.84
1784122,3.0,jaggers lady,4.0,29.8,16.8,73.0,8.8470,22.783,1003071153,390,5,shepparton,2024-03-05,poo,poo,71.0,Shepparton (AUS) 5th Mar,37.648780,21.7389,686.67
1784123,4.0,lektra flying,3.0,32.6,3.7,66.0,8.8120,22.848,1003071153,390,5,shepparton,2024-03-05,poo,poo,1219.0,Shepparton (AUS) 5th Mar,5.649120,4.0403,6456.50